language: java
jdk: openjdk8
git:
  depth: false

stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
  - script: sbt publishLocal

  - stage: release
    script:
      - sbt ci-release
  - name: Update README
    stage: release
    script:
      - amm scripts/generate-readme.sc
    deploy:
      provider: pages
      keep_history: true
      github_token: $GH_TOKEN
      target_branch: master
      on:
        branch: /^v\d+\.\d+.*$/

before_install:
- export PATH="$HOME/.bin:$PATH"
- ./scripts/.travis-setup.sh

cache:
  directories:
  - $HOME/.bin
  - $HOME/.cache
  - $HOME/.sbt
branches:
  only:
  - master
  - /^v\d+\.\d+.*$/ # tagged versions
